package com.shop.product;

import com.shop.product.domain.Category;
import com.shop.product.dto.CategoryResponse;
import org.mapstruct.Mapper;

import java.util.List;

/**
 * Entity → DTO mapper for categories (design pattern: <b>Mapper</b>, generated by MapStruct).
 */
@Mapper(componentModel = "spring")
public interface CategoryMapper {

    CategoryResponse toResponse(Category category);

    List<CategoryResponse> toResponseList(List<Category> categories);
}
