package com.shop.product;

import com.shop.product.domain.Product;
import com.shop.product.dto.ProductCreateRequest;
import com.shop.product.dto.ProductResponse;
import com.shop.product.dto.ProductUpdateRequest;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

/**
 * Entity ↔ DTO mapper for products (design pattern: <b>Mapper</b>, generated by MapStruct).
 * Keeps the {@link Product} entity off the API boundary and removes hand-written boilerplate.
 *
 * <p>{@code category} is resolved by {@code ProductService} (it must be loaded/validated against
 * the DB), so it is intentionally ignored on write mappings; {@code id}/{@code createdAt} are
 * managed by JPA and never set from request payloads.</p>
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface ProductMapper {

    @Mapping(target = "categoryId", source = "category.id")
    @Mapping(target = "categoryName", source = "category.name")
    ProductResponse toResponse(Product product);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "category", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    Product toEntity(ProductCreateRequest request);

    @Mapping(target = "id", ignore = true)
    @Mapping(target = "category", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    void updateEntity(@MappingTarget Product product, ProductUpdateRequest request);
}
