package com.shop.cart;

import com.shop.cart.domain.CartItem;
import com.shop.cart.dto.CartItemResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.List;

/**
 * Entity → DTO mapper for cart lines (design pattern: <b>Mapper</b>, generated by MapStruct).
 * Keeps the {@code CartItem}/{@code Cart} entities off the API boundary.
 *
 * <p>{@code unitPrice} comes from the product's <b>current</b> price (the cart is a live offer);
 * {@code lineTotal} is computed as {@code price × quantity}. Cart-level totals are aggregated by
 * {@code CartService} from these line DTOs.</p>
 */
@Mapper(componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        imports = java.math.BigDecimal.class)
public interface CartMapper {

    @Mapping(target = "productId", source = "product.id")
    @Mapping(target = "productName", source = "product.name")
    @Mapping(target = "unitPrice", source = "product.price")
    @Mapping(target = "lineTotal",
            expression = "java(item.getProduct().getPrice().multiply(BigDecimal.valueOf(item.getQuantity())))")
    CartItemResponse toItemResponse(CartItem item);

    List<CartItemResponse> toItemResponses(List<CartItem> items);
}
