package com.shop.order;

import com.shop.order.domain.Order;
import com.shop.order.domain.OrderItem;
import com.shop.order.dto.OrderItemResponse;
import com.shop.order.dto.OrderResponse;
import com.shop.order.dto.OrderSummaryResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

/**
 * Entity → DTO mapper for orders (design pattern: <b>Mapper</b>, generated by MapStruct). Keeps
 * the {@code Order}/{@code OrderItem} entities off the API boundary.
 *
 * <p>Line DTOs expose the price/name <b>snapshots</b> stored on {@code OrderItem} (not the live
 * product), so the response is stable regardless of later catalog changes. {@code lineTotal} is
 * computed from the snapshot {@code unitPrice × quantity}.</p>
 */
@Mapper(componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        imports = java.math.BigDecimal.class)
public interface OrderMapper {

    @Mapping(target = "productId", source = "product.id")
    @Mapping(target = "lineTotal",
            expression = "java(item.getUnitPrice().multiply(BigDecimal.valueOf(item.getQuantity())))")
    OrderItemResponse toItemResponse(OrderItem item);

    OrderResponse toResponse(Order order);

    OrderSummaryResponse toSummary(Order order);
}
